import ForgotPassword from 'component/ForgotPassword'
import Login from 'component/Login'
import Register from 'component/Register'
import Cookies from 'js-cookie'
import Home from 'pages/Home'
import ResetPassword from 'pages/ResetPassword'
import React, { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { BrowserRouter as Router, Switch, Route } from 'react-router-dom'
import { Provider } from 'react-redux' //Generated by tailwind
import authReducer from './store/authStore'
import { createStore } from 'redux'
const authStore = createStore(authReducer)

const App = () => {
  const state = useSelector((i) => i)
  const dispatch = useDispatch()

  useEffect(() => {
    let user = Cookies.getJSON('authInfo')
    if (user !== undefined) dispatch({ type: 'CHECK_AUTH_SUCCESS' })
    else dispatch({ type: 'CHECK_AUTH_FAIL' })
  }, [])

  return (
    <Router>
      <Switch>
        <Route path="/register" children={<Register />}></Route>
        <Route path="/login" children={<Login />}></Route>
        <Route path="/reset/:token" children={<ResetPassword />}></Route>
        <Route path="/forgot-password" children={<ForgotPassword />}></Route>
        <Route path="/" children={<Home />}></Route>
      </Switch>
    </Router>
  )
}

export default App
