import React from 'react'
import ReactDOM from 'react-dom'
import App from './App'
import authReducer from './store/authStore'
import { createStore } from 'redux'
import * as serviceWorker from './serviceWorker'
import 'index.css' // Generated by tailwind
import { Provider } from 'react-redux'
import * as firebase from 'firebase'

const firebaseConfig = {
  apiKey: process.env.REACT_APP_FIREBASEKEY,
  authDomain: 'ecommerce-intern-672fb.firebaseapp.com',
  projectId: 'ecommerce-intern-672fb',
  storageBucket: 'ecommerce-intern-672fb.appspot.com',
  messagingSenderId: '927142665834',
  appId: '1:927142665834:web:dbfcdd494d837d1a927413',
  measurementId: 'G-VFD5G9Q43J',
}
// Initialize Firebase
firebase.initializeApp(firebaseConfig)
firebase.analytics() //Generated by tailwind

const authStore = createStore(authReducer)

ReactDOM.render(
  <React.StrictMode>
    <Provider store={authStore}>
      <App />
    </Provider>
  </React.StrictMode>,
  document.getElementById('root')
)

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister()
