import React from 'react'
import ReactDOM from 'react-dom'
import App from './App'
import authReducer from './store/authStore'
import { createStore } from 'redux'
import * as serviceWorker from './serviceWorker'
import 'index.css' // Generated by tailwind
import { Provider } from 'react-redux' //Generated by tailwind

const authStore = createStore(authReducer)

ReactDOM.render(
  <React.StrictMode>
    <Provider store={authStore}>
      <App />
    </Provider>
  </React.StrictMode>,
  document.getElementById('root')
)

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister()
